/* Autogenerated by png2wx.pl on Mon Nov 25 23:02:41 2019 */
#ifndef ACTISENSE_ICONS_H
#define ACTISENSE_ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_actisense_black;
extern wxBitmap *_img_actisense_white;
extern wxBitmap *_img_actisense_logo_16;
extern wxBitmap *_img_actisense_logo_32;

#endif /* ACTISENSE_ICONS_H */
